### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/authy#26]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳
